import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const routePath = new URL("../app/api/generate/route.ts", import.meta.url);
const runtimePath = new URL("../app/skill-runtime.ts", import.meta.url);
const compositePath = new URL("../app/real-scene-paper-composite.ts", import.meta.url);
test("gathered scenes combines a source-aligned art layer with semantic source masks", async () => {
  const route = await readFile(routePath, "utf8");
  const runtime = await readFile(runtimePath, "utf8");
  const composite = await readFile(compositePath, "utf8");

  assert.doesNotMatch(route, /gatheredStyleReferences/);
  assert.doesNotMatch(route, /plan\.compositionMode/);
  assert.match(route, /segmentPhotoSubjects/);
  assert.match(route, /segmentPhotoSubjects\(body\.analysisImage \|\| body\.image\)/);
  assert.match(route, /semanticMinimum 不是对象清单，而是完成叙事必须一起成立的关系/);
  assert.match(route, /spatialInvariants 必须明确这些元素的相对位置、遮挡和方向/);
  assert.match(route, /boundaryGuide 是原图坐标中的二维撕口折线/);
  assert.match(route, /photoEvidenceSide 表示折线哪一侧保留原摄影/);
  assert.match(route, /photoEvidenceType 决定真实摄影证据/);
  assert.match(route, /layoutArchetype 从五类关系构图中选择/);
  assert.match(route, /focusMode/);
  assert.match(route, /targetPhotoShare/);
  assert.match(route, /preserveOnlyPrimary: false/);
  assert.match(route, /同取景、同透视、主体同位置同尺度/);
  assert.match(route, /沿语义轮廓恢复真实原图像素/);
  assert.match(route, /ARK_GATHERED_IMAGE_MODELS/);
  assert.match(route, /doubao-seedream-4-0-250828.*doubao-seedream-4-5-251128.*doubao-seedream-5-0-lite-260128/);
  assert.match(route, /第二张图是用户最终会看到的候选成图/);
  assert.doesNotMatch(route, /真正的纤维撕口由网页/);
  assert.match(route, /layout: "scene-fragment"/);
  assert.match(route, /const usesGatheredComposite = adapter\.id === "gathered-scenes"/);
  assert.match(route, /subjectMasks: gatheredSegmentation\?\.masks/);
  assert.match(route, /semanticMinimum: plan\.semanticMinimum/);
  assert.match(route, /boundaryGuide: plan\.boundaryGuide/);
  assert.match(route, /photoEvidenceSide: plan\.photoEvidenceSide/);
  assert.match(route, /edgeForegroundSides: plan\.edgeForegroundSides/);
  assert.match(route, /平行横向分层/);
  assert.match(route, /天空必须继承原图的云量、云形、色相和明暗/);
  assert.match(route, /最多一条贯穿画面的主撕口/);
  assert.match(route, /通用云朵/);
  assert.match(route, /网页先恢复关系场景，再用主体分割补强关键轮廓/);
  assert.match(route, /自动质检判定第一次候选不合格/);
  assert.match(route, /autoRetried/);
  assert.match(runtime, /同取景、同透视、同主体坐标的纸刊艺术层/);
  assert.match(runtime, /主体分割负责找出叙事主体与可靠前景/);
  assert.match(runtime, /沿真实语义轮廓恢复用户上传照片的原始像素/);
  assert.doesNotMatch(runtime, /网页最后沿计划撕口覆盖/);
  assert.match(runtime, /数码蒙版感/);
  assert.match(composite, /createEdgeForegroundMask/);
  assert.match(composite, /const allSides: EdgeForegroundSide\[\] = \["top", "right", "bottom", "left"\]/);
  assert.match(composite, /horizontalBandScore/);
  assert.match(composite, /flatPosterizationScore/);
  assert.match(composite, /const artifactScore = bandScore \+ flatScore/);
  assert.match(composite, /artifactScore >= 3/);
  assert.doesNotMatch(composite, /const step = 24/);
  assert.doesNotMatch(composite, /targetLuminance/);
  assert.match(composite, /spec\.edgeForegroundSides/);
});
