import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const routePath = new URL("../app/api/generate/route.ts", import.meta.url);
const runtimePath = new URL("../app/skill-runtime.ts", import.meta.url);
test("gathered scenes generates and reviews one complete paper-collage poster", async () => {
  const route = await readFile(routePath, "utf8");
  const runtime = await readFile(runtimePath, "utf8");

  assert.doesNotMatch(route, /gatheredStyleReferences/);
  assert.doesNotMatch(route, /plan\.compositionMode/);
  assert.doesNotMatch(route, /segmentPhotoSubjects\(body\.analysisImage \|\| body\.image\)/);
  assert.match(route, /锁定让照片仍然成立的主体和空间关系/);
  assert.match(route, /摄影锚点的轮廓沿当前照片里的树冠、水线、岸线、岩石、屋檐、道路或动作关系/);
  assert.match(route, /focusMode/);
  assert.match(route, /targetPhotoShare/);
  assert.match(route, /保留原照片，把它做成一张纸感拼接海报并直接输出完整成图/);
  assert.match(route, /模型一次性生成并直接输出完整纸感拼接海报/);
  assert.match(route, /ARK_GATHERED_IMAGE_MODELS/);
  assert.match(route, /DASHSCOPE_API_KEY/);
  assert.match(route, /qwen-image-3\.0-pro/);
  assert.match(route, /generateQwenImageCandidate/);
  assert.match(route, /provider: "dashscope"/);
  assert.match(route, /保留原图里的人物\/物体主体、画面构图和真实原生色彩/);
  assert.match(route, /简化杂乱背景，改成干净柔和的大块色块/);
  assert.match(route, /低克制度高饱和结构配色/);
  assert.match(route, /杜绝廉价贴纸、模板网红感/);
  assert.match(route, /doubao-seedream-5-0-lite-260128.*doubao-seedream-4-5-251128.*doubao-seedream-4-0-250828/);
  assert.match(route, /第二张图是用户最终会看到的候选成图/);
  assert.match(route, /插画场实际着墨明显不足15%/);
  assert.match(route, /微文字放在额外纸片、标签或卡片上/);
  assert.doesNotMatch(route, /layout: "scene-fragment"/);
  assert.doesNotMatch(route, /subjectMasks: gatheredSegmentation/);
  assert.match(route, /若用户没有谈到文字，可从照片可见的天气、地点氛围、运动或静谧感中创作一行/);
  assert.match(route, /自动质检判定第一次候选不合格/);
  assert.match(route, /autoRetried/);
  assert.match(runtime, /由图像模型一次性生成完整平面扫描成品/);
  assert.match(runtime, /不使用主体分割、浏览器抠图、滤镜叠加或二次拼接/);
  assert.match(runtime, /数码蒙版/);
});
